# 语言，默认简体中文
# 当前支持设置为：zh_cn / en / zh_tc
# Language, default is zh_cn (Simplified Chinese)
# Now support: zh_cn / en / zh_tc
language: zh_cn

# 必选项，存储类型设置
# 默认为json，可选项：json / mysql
# Required, storage type settings
# Default is json, optional: json / mysql
storage: json

# MySQL数据库设置
# MySQL database settings
mysql:
  host: localhost
  port: 3306
  database: meow_uid
  username: meow_uid
  password: password