name: MeowTrashCan
main: com.meow.meowtrashcan.MeowTrashCan
version: 1.0
api-version: 1.16
description: MeowTrashCan - 支持翻垃圾的跨服垃圾桶插件

commands:
  meowtrashcan:
    description: MeowTrashCan主命令
    usage: /<command> <throw|dig|reload>
    aliases:
      - mtc

permissions:
  meowtrashcan.throw:
    description: Permission to throw items into the trash bin.
    default: true
  meowtrashcan.dig:
    description: Permission to flip through trash.
    default: true
  meowtrashcan.reload:
    description: Permission to reload the plugin configuration.
    default: op